import { User } from "../types/User";

export const fetchUsers = (): User[] => {
  return [
    {
      id: 1,
      first_name: "David",
      last_name: "Garcia",
      username: "david.garcia_478",
      age: 36,
      marital_status: "unmarried",
      is_employed: false,
      is_founder: false,
    },
    {
      id: 2,
      first_name: "Charlotte",
      last_name: "Miller",
      username: "charlotte.miller_703",
      age: 48,
      marital_status: "married",
      is_employed: true,
      is_founder: false,
    },
    {
      id: 3,
      first_name: "James",
      last_name: "Anderson",
      username: "james.anderson_740",
      age: 57,
      marital_status: "married",
      is_employed: true,
      is_founder: false,
    },
    {
      id: 4,
      first_name: "Ava",
      last_name: "Brown",
      username: "ava.brown_618",
      age: 30,
      marital_status: "unmarried",
      is_employed: false,
      is_founder: false,
    },
    {
      id: 5,
      first_name: "Liam",
      last_name: "Jones",
      username: "liam.jones_190",
      age: 20,
      marital_status: "married",
      is_employed: false,
      is_founder: false,
    },
    {
      id: 6,
      first_name: "Emily",
      last_name: "Harris",
      username: "emily.harris_112",
      age: 34,
      marital_status: "married",
      is_employed: false,
      is_founder: false,
    },
    {
      id: 6,
      first_name: "Charlotte",
      last_name: "Smith",
      username: "charlotte.smith_883",
      age: 51,
      marital_status: "unmarried",
      is_employed: true,
      is_founder: false,
    },
    {
      id: 7,
      first_name: "Sophia",
      last_name: "Harris",
      username: "sophia.harris_368",
      age: 54,
      marital_status: "unmarried",
      is_employed: false,
      is_founder: false,
    },
    {
      id: 8,
      first_name: "Lucas",
      last_name: "Wilson",
      username: "lucas.wilson_394",
      age: 43,
      marital_status: "married",
      is_employed: true,
      is_founder: false,
    },
    {
      id: 9,
      first_name: "Sophia",
      last_name: "Wilson",
      username: "sophia.wilson_318",
      age: 23,
      marital_status: "married",
      is_employed: false,
      is_founder: false,
    },
    {
      id: 10,
      first_name: "Henry",
      last_name: "Martin",
      username: "henry.martin_133",
      age: 33,
      marital_status: "unmarried",
      is_employed: true,
      is_founder: false,
    },
    {
      id: 11,
      first_name: "Lucas",
      last_name: "Harris",
      username: "lucas.harris_919",
      age: 30,
      marital_status: "married",
      is_employed: false,
      is_founder: false,
    },
    {
      id: 12,
      first_name: "Ethan",
      last_name: "Martin",
      username: "ethan.martin_258",
      age: 49,
      marital_status: "unmarried",
      is_employed: false,
      is_founder: false,
    },
    {
      id: 13,
      first_name: "Alice",
      last_name: "Robinson",
      username: "alice.robinson_281",
      age: 52,
      marital_status: "unmarried",
      is_employed: true,
      is_founder: false,
    },
    {
      id: 14,
      first_name: "David",
      last_name: "Garcia",
      username: "david.garcia_858",
      age: 57,
      marital_status: "unmarried",
      is_employed: false,
      is_founder: false,
    },
    {
      id: 15,
      first_name: "Henry",
      last_name: "Martin",
      username: "henry.martin_260",
      age: 26,
      marital_status: "married",
      is_employed: true,
      is_founder: false,
    },
    {
      id: 16,
      first_name: "Michael",
      last_name: "Martin",
      username: "michael.martin_867",
      age: 54,
      marital_status: "married",
      is_employed: false,
      is_founder: false,
    },
  ];
};
